"""create rides

Revision ID: 44f98000e140
Revises: fd63641eaa5d
Create Date: 2026-07-10 18:39:53.789399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f98000e140'
down_revision: Union[str, Sequence[str], None] = 'fd63641eaa5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('distance_km', sa.Float(), nullable=False))
    op.add_column('rides', sa.Column('estimated_duration', sa.Float(), nullable=False))
    op.alter_column('rides', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('rides', 'distance')
    op.drop_column('rides', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('duration', sa.FLOAT(), nullable=False))
    op.add_column('rides', sa.Column('distance', sa.FLOAT(), nullable=False))
    op.alter_column('rides', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rides', 'estimated_duration')
    op.drop_column('rides', 'distance_km')
    # ### end Alembic commands ###
